### ISSUE TITLE
Could not load file or assembly 'Dnn.WebAnalyticsLinqToSql' or one of its dependencies

### ISSUE THREAD

**Issue by programatix** [DNNCommunity/Dnn.WebAnalytics#37]
I installed Dnn.WebAnalytics and I get the following log event whenever the VisitorJob is run.
```
THREAD ID:13
TYPE:Dnn.WebAnalyticsLinqToSql.VisitorJob, Dnn.WebAnalyticsLinqToSql
EXCEPTION:Could not load file or assembly 'Dnn.WebAnalyticsLinqToSql' or one of its dependencies. The system cannot find the file specified.
RESCHEDULED FOR:5/4/2021 8:54:20 PM
SOURCE:STARTED_FROM_SCHEDULE_CHANGE
ACTIVE THREADS:0
FREE THREADS:1
READER TIMEOUTS:0
WRITER TIMEOUTS:0
IN PROGRESS:0
IN QUEUE:9
```
and
```
AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:52701eeb-178f-47b2-bc0c-03d2a4bcca77
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:s0nVKrlgDULPGdBb7Zi3l+WpHj4=
Message:Could not load file or assembly 'Dnn.WebAnalyticsLinqToSql' or one of its dependencies. The system cannot find the file specified.
StackTrace:
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at DotNetNuke.Services.Scheduling.ProcessGroup.GetSchedulerClient(IServiceProvider services, String strProcess, ScheduleHistoryItem objScheduleHistoryItem)
   at DotNetNuke.Services.Scheduling.ProcessGroup.Run(ScheduleHistoryItem objScheduleHistoryItem)
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
```

The IIS and SQL Server are running on different machines and both are running Windows Server 2019.

I tried checking this repo and can't seem to find anything about `Dnn.WebAnalyticsLinqToSql` except the install and uninstall scripts.

**Comment by programatix** [comment]
Turns out that I need to manually rename `Dnn.WebAnalyticsLinqToSql` to `Dnn.WebAnalytics` in the Scheduler. At first I thought the exceptions are the reason why the Visitors Online module is not working, but after resolving the exceptions, it still doesn't work. The map is displayed but the values for Visitors/Users Online are always 0.

Update: Map issue is related to https://github.com/DNNCommunity/Dnn.WebAnalytics/issues/34. I tried putting the key in web.config but it doesn't work.
